### ISSUE TITLE
resource-download: progress: return name

### ISSUE THREAD

**Issue by FIr3baL** [beyond-all-reason/spring-launcher#22]
Please return name of resource-download on DownloadProgress instead of destination

after starting a resource-download with arguments:
- name = "105.1.1-1354-g72b2d55 BAR105",
- type = "resource",
- resource = {
    url = "https://github.com/beyond-all-reason/spring/releases/download/spring_bar_%7BBAR105%7D105.1.1-1354-g72b2d55/spring_bar_.BAR105.105.1.1-1354-g72b2d55_windows-64-minimal-portable.7z",
    destination = "engine//105.1.1-1354-g72b2d55 bar",
    extract = true
}

launcher returns DownloadProgress with name = destination
- progress = 0.2568467
- total = 16441672
- name = engine//105.1.1-1354-g72b2d55 bar

**Comment by p2004a** [comment]
Resolved per https://github.com/beyond-all-reason/spring-launcher/pull/25#issuecomment-1586198491
