### ISSUE TITLE
resource-download: finished: return name

### ISSUE THREAD

**Issue by FIr3baL** [beyond-all-reason/spring-launcher#23]
1. Please return the name of the resource-download on DownloadFinished
2. Stop sending endless DownloadFinished commands with name="Skipping..." (see. beneath)

After starting a resource-download with arguments:
- name = "105.1.1-1354-g72b2d55 BAR105",
- type = "resource",
- resource = {
    url = "https://github.com/beyond-all-reason/spring/releases/download/spring_bar_%7BBAR105%7D105.1.1-1354-g72b2d55/spring_bar_.BAR105.105.1.1-1354-g72b2d55_windows-64-minimal-portable.7z",
    destination = "engine//105.1.1-1354-g72b2d55 bar",
    extract = true
}

1. launcher returns DownloadFinished without an identifying parameter once
- isSuccess = true
- isAborted = false

3. then sends endless returns of  DownloadFinished with
- isSuccess = true
- isAborted = false
- name = Skipping C:\Beyond-All-Reason\data\engine\105.1.1-1354-g72b2d55 bar: already exists.

**Comment by p2004a** [comment]
Resolved per https://github.com/beyond-all-reason/spring-launcher/pull/25#issuecomment-1586198491
