### ISSUE TITLE
Please change the game's config directory in AppImage

### ISSUE THREAD

**Issue by Brensom** [beyond-all-reason/spring-launcher#36]
Please change the game's config directory from $HOME/Desktop to $HOME/.config.
And please change the game files directory to /opt/ or simple $HOME.

**Comment by FIr3baL** [comment]
@p2004a Can u move this to launcher ? thx

**Comment by p2004a** [comment]
@Brensom game files directory is not `$HOME/Desktop`, it's `$XDG_STATE_HOME` since last release. Before then, it was `Documents` (or whatever electron logic picked as "documents" folder), and if launcher detects files there, it uses that location to not break existing installs.
